### ISSUE TITLE
Transitioning to GCC-5

### ISSUE THREAD

**Issue by yesimon** [staticfloat/homebrew-julia#153]
Got this
```
simon@nitrogen ~> julia
Warning: error initializing module LinAlg:
ErrorException("error compiling __init__: error compiling check_blas: error compiling openblas_get_config: could not load module libopenblas: dlopen(libopenblas.dylib, 1): Library not loaded: /u
sr/local/lib/gcc/4.9/libgfortran.3.dylib
  Referenced from: /usr/local/opt/openblas-julia/lib/libopenblas.dylib
  Reason: image not found")
```
Which is readily cured by
`brew install --build-from-source openblas-julia`

This may be a tricky moving target to update the bottles when "a reasonable proportion" of people have upgrade to gcc-5.

**Comment by staticfloat** [comment]
This should already be fixed by 33abbf156bbf0721c6058091f616f976a2cfd700.  You should be able to `brew update && brew upgrade` to get the latest `gcc` and `openblas-julia`.

**Comment by yesimon** [comment]
Thanks, didn't update brew which was the problem.

**Comment by staticfloat** [comment]
I'm going to close this, assuming that your issues have been resolved.  Please comment here or open a new issue if problems persist.

**Comment by tcfuji** [comment]
Still getting this error.

```julia
$ julia
Warning: error initializing module LinAlg:
ErrorException("error compiling __init__: error compiling check_blas: error compiling openblas_get_config: could not load module libopenblas: dlopen(libopenblas.dylib, 1): Library not loaded: /usr/local/lib/gcc/4.9/libgfortran.3.dylib
  Referenced from: /usr/local/opt/openblas-julia/lib/libopenblas.dylib
  Reason: image not found")
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.3.9 (2015-05-30 11:24 UTC)
 _/ |\__'_|_|_|\__'_|  |
|__/                   |  x86_64-apple-darwin14.0.0

julia>

```
```
$ brew upgrade julia
Error: staticfloat/julia/julia 0.3.9_1 already installed

**Comment by staticfloat** [comment]
What happens if you `brew upgrade openblas-julia`?
-E

**Comment by tcfuji** [comment]
```
$ brew update
Updated Homebrew from 6f4494d2 to 3feb5086.
==> New Formulae
homebrew/science/ascii_plots		homebrew/x11/wcm
homebrew/science/wfdb			protobuf-swift
homebrew/x11/gimp			sparse
==> Updated Formulae
awscli			   homebrew/science/r	      pre-commit
czmq			   homebrew/science/salmon    pushpin
fleetctl		   homebrew/x11/meld	      scm-manager
fontforge		   homebrew/x11/yarp	      sslmate
h2o			   imapfilter		      uudeview
harfbuzz		   mariadb		      zeromq
homebrew/science/blasr	   mongrel2		      zurl
$ brew upgrade openblas-julia
Error: staticfloat/julia/openblas-julia 0.2.12_1 already installed

**Comment by staticfloat** [comment]
What happens if you do `brew rm openblas-julia; brew cleanup; brew install openblas-julia`?

**Comment by tcfuji** [comment]
The error is gone now.

Thanks.

**Comment by staticfloat** [comment]
Great.  I'm not sure why that got stuck, but I'm glad it's fixed now!

**Comment by mlhetland** [comment]
Just an FYI: I had the same problem, and the cleanup-solution worked for me as well.
