### ISSUE TITLE
Julia build failing -- openblas linking issue?

### ISSUE THREAD

**Issue by iamed2** [staticfloat/homebrew-julia#161]
For some reason the Julia build can't find openblas. I've tried uninstalling every dependency from this tap and reinstalling, to no avail.

This is the error:
```bash
error during bootstrap:
LoadError(at "sysimg.jl" line 249: LoadError(at "util.jl" line 252: ErrorException("error compiling blas_vendor: could not load library 'libopenblas'
dlopen(libopenblas.dylib, 1): image not found")))
```

The last command run (the erring one) onwards: https://gist.github.com/iamed2/0efd0bd41fc0caa2c386

**Comment by mlhetland** [comment]
Related to #159?

**Comment by mlhetland** [comment]
Or, well, no … but the `brew rm --force openblas-julia; brew install openblas-julia` bit, I mean. (Having the same problem at the moment.)

**Comment by mlhetland** [comment]
No – sorry for adding noise here. I have the same problem, but that “fix” didn't really help at all in this case. :-}

**Comment by iamed2** [comment]
Confirmed that I can build julia from git directly, but I have to use `OPENBLAS_TARGET_ARCH=HASWELL`

**Comment by bosmacs** [comment]
I had the same problem, and worked around if (for the time being, at least) by reinstalling `openblas-julia` and linking it system-wide before installing julia, i.e.
~~~
brew reinstall openblas-julia
brew link --force openblas-julia
brew reinstall julia --HEAD
~~~
After this, I think `openblas-julia` can be unlinked again.

**Comment by mlhetland** [comment]
That did seem to help with the compilation, but I seem to get problems with `suite-sparse-julia`:
```julia
$ julia
Warning: error initializing module CHOLMOD:
ErrorException("could not load library 'libsuitesparseconfig'
dlopen(libsuitesparseconfig.dylib, 1): image not found")
```

**Comment by staticfloat** [comment]
Thanks for alerting me to this! It turns out this is because due to Julia system image build changes, we need to generate different system images for debug and release builds, and previously we were doing the `make debug` step after removing some symlinks to `openblas` and `suite-sparse`.  I've pushed a fix that should work for you guys.

**Comment by iamed2** [comment]
Thanks for the response @staticfloat !

Unfortunately the fix you've provided gives the error @mlhetland mentioned above, even after reinstalling openblas-julia and suite-sparse-julia.

**Comment by staticfloat** [comment]
Please try again now, I've made another commit that should fix up the issue you are seeing.

**Comment by mlhetland** [comment]
I just tried:
```
$ brew update && brew reinstall --HEAD julia
```
But when starting Julia, I still get the problem loading `libsuitesparseconfig`…

**Comment by iamed2** [comment]
@mlhetland you have to get the `staging` branch of this repo, which is kind of hard.

I ran the install with the update and everything's fixed, thanks!

**Comment by mlhetland** [comment]
Oh, right! I see now that `master` hasn't changed in a while :smile:

**Comment by mlhetland** [comment]
OK, just to confirm – after…
```
$ cd /usr/local/Library/Taps
$ mkdir staticfloat && cd staticfloat
$ git clone https://github.com/staticfloat/homebrew-julia.git 
$ cd homebrew-julia && git checkout remotes/origin/staging
$ brew tap --repair
$ brew reinstall --HEAD julia
```
… it works for me, too.

**Comment by staticfloat** [comment]
Great, sorry about the `staging` confusion.   This has been merged into `master` now, so everyone can enjoy!
