### ISSUE TITLE
Building IJulia and ZMQ on Julia-0.6

### ISSUE THREAD

**Issue by pstaabp** [staticfloat/homebrew-julia#240]
@staticfloat 

I was trying the Julia-0.6-dev2 version of julia and trying to build the IJulia package.  There was an error when building ZMQ of:

```
=====================================[ ERROR: ZMQ ]==================

LoadError: SystemError: unable to read directory /Users/pstaab/.julia/v0.6/Homebrew/deps/usr/Library/Taps/staticfloat/homebrew-juliatranslated: No such file or directory
```
and in fact there is no such directory.  However, that directory does exist when building under 0.5.  I had no errors installing and building `Homebrew` in Julia 0.6

**Comment by staticfloat** [comment]
Hmmm, I pushed a fix to `Homebrew.jl` not too long ago that should have fixed this, can you `Pkg.update()` and try again?

**Comment by pstaabp** [comment]
I just upgraded to the final release of 0.6 and a `Pkg.update()` didn't change the error.  
Also, removing Homebrew and reinstalling it results in the same error.  That is, the directory listed above is still missing.

**Comment by staticfloat** [comment]
Hmmm, if you run `using Homebrew; Homebrew.install_brew()` does that fix things?

**Comment by pstaabp** [comment]
That works for me now.  Seems like it show work without these however.  And everything worked well is julia-0.5.
